segmentio/analytics-node

- package.json
This allows our license scraper to automatically pick up the license on the
package. I referred to https://docs.npmjs.com/files/package.json#license
for the syntax.
> Adds a "license" field to package.json

- .travis.yml
- lib/index.js
- package.json
- test/index.js
This changes the behavior of setting end-to-end messageIds, so
that the client library now generates individual ones per message
rather than a single group of them per batch.
It also increases the entropy, increasing them to 32 characters.
> increase messageId entropy, and include one id per message

- bin/analytics
- package.json
While working on a revamped simulator, I've decide it's best to create docker containers for each library. In addition, it's way easier `docker run` things that have a CLI, so I've added one here. It also turned out this tool could be useful for success engineers or for debugging, so I've created this as a separate PR after discussing with @calvinfo.
The big idea is that you add a `$SEGMENT_WRITE_KEY` to your env and then you can run the following commands:
```bash
$ analytics track <event> [options]
$ analytics identify [options]
$ analytics group [options]
$ analytics alias [options]
$ analytics page [options]
```
All the options are consistent throughout the commands, which you can see by using `--help`.
**NOTE:** This adds 1 more dependency to `analytics-node` itself, which is …
> Adding a CLI

- lib/index.js
- package.json
I needed this validation logic elsewhere, so I pulled it out and moved it to the [loosely-validate-event](https://github.com/segmentio/loosely-validate-event) module. The code is basically a 1:1, just stylistic changes. This patch pulls in this new module and offloads all validation logic to it.
@segmentio/gateway
> Replace validation with `@segment/loosely-validate-event`

- lib/index.js
- package.json
- test/index.js
I just spent over an hour trying to figure out why an event wasn't showing up. The reason was I was POSTing to `https://api.segment.tld//v1/batch` rather than `https://api.segment.tld/v1/batch`.
@segmentio/gateway @fouad
> remove trailing slash on `.host`

- lib/index.js
- test/index.js
FIx #79 :)
I first tried to add it to the context, as it's where the library version is, but per #79 it should be in `_metadata`.
CC: @myclamm 
(mostly based on this github search: https://github.com/search?q=org%3Asegmentio+_metadata&type=Code)
> Add node version to messages via _metadata

- lib/index.js
Keeps various dev tools from complaining about missing parameters: http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values
> use correct optional syntax for JSDOC

- .travis.yml
- README.md
- RELEASING.md
- circle.yml
This patch replaces Travis with CircleCI. This prevents the context-switching between Travis and Circle (since we use Circle for nearly everything else), and gives us more flexibility for handling builds.
This patch also introduces automatically published builds (to npm) and automatically generated `analytics-node.js` versions.
Closes #80.
@segmentio/gateway 
----
NOTE - Travis build is failing because I removed the `.travis.yml` file. Once approved, I'll disable Travis and rebuild.
> replace Travis with CircleCI

- test/index.js
#82 was merged _after_ #84, so the "screen" test didn't exist (therefore couldn't be "fixed").
@segmentio/gateway
> test: add `_metadata` to "screen" assertion

- lib/index.js
- test/index.js
Follow up to @nathanpeck's work on https://github.com/segmentio/analytics-node/pull/54. Rebased and modified a test.
To recap, this PR makes reset timer work as an interval, instead of resetting it on each `enqueue()` call.
> Reset timer on flush

- bin/analytics
- circle.yml
- lib/index.js
- package.json
- test/index.js
This PR brings a breaking change - inability to create an instance without a `new` keyword, which is a JavaScript limitation.
Also removes the dependency on `lodash/extend` and `clone`, since those can be replaced with `Object.assign()`.
Tests are failing, because I haven't modified them for the above mentioned change. I would like to merge #108 first, to avoid a merge conflict.
> Convert to ES6

- index.js
- test.js
Refs #53.
See https://github.com/segmentio/analytics-node/issues/53#issuecomment-317517930.
Since the next release is a major one, there's no backwards compatibility with `flushAfter` naming.
> Rename flushAfter to flushInterval

- index.js
- test.js
Refs https://github.com/segmentio/analytics-node/issues/53.
As correctly pointed out in https://github.com/segmentio/analytics-node/issues/53, the client should flush right after it receives a first message. This PR implements that behavior.
> Flush on first message

- index.js
- test.js
- timeout was not enabled nor configurable previously
- retries were hardcoded to `3` and not configurable
Fixes https://github.com/segmentio/analytics-node/issues/119.
I looked into writing tests, but you've got the [mock server set up in a `before`](https://github.com/segmentio/analytics-node/blob/4290503572a7c9661661dbcafef75b573cdbda0b/test.js#L34-L49) so I would need to refactor the tests to allow a test or two to configure the server to conditionally fail with a retryable error or not respond. If the lack of tests is a blocker, I can give it a try.
Thanks!
> Allow configuring retries and timeout.

- index.js
- package.json
- test.js
When moving to Axios, I didn't add the write key to the requests. Our
tests didn't catch this, so I figured we were safe to release a new
version.
This patch corrects that, and ensures this will never happen again by
updating the tests.
Closes #127
> add write key to request

- index.js
- test.js
This patch adds the `User-Agent` header to all requests made to the Segment API. In the event we need to track how many requests are coming in from a specific version of the library in the future, we can check CDN logs/stats for this header.
> add useragent

- circle.yml
- test.js
Ref: https://paper.dropbox.com/doc/analytics-node-E2E-Test-9oavh3DFcFBXuqCJBe1o9
> Add an end to end test case.

- index.js
- package.json
- test.js
Ref: https://segment.atlassian.net/browse/LIB-29
Our API truncates bignum values. This is problematic because this library has historically accepted Numbers as userIds and anonymousIds. To workaround the truncation, this library needs to stringify userId and anonymousId on the client.
The test cases are numbers that will be truncated in Node, e.g. node -e "console.log(157963456373623802 + 1)".
> Stringify userId and anonymousId

- circle.yml
Instead of setting this up via the config file, we'll do this as an encrypted variable via the UI https://circleci.com/gh/segmentio/analytics-node/edit#env-vars.
Otherwise the `RUN_E2E_TESTS` variable is true for contributors, but their builds won't have the `RUNSCOPE_TOKEN` which is encrypted and not available to them. This causes contributor PRs to fail as the test suite tries to run the end to end tests without the appropriate tokens.
> Remove RUN_E2E_TESTS from Circle config.

- index.js
- test.js
Previously we were only retrying network errors or a 5xx error on an idempotent request (GET, HEAD, OPTIONS, PUT or DELETE).
The latter doesn't really guard/apply to us since we use POST for uploading messages. Our POST requests are idempotent since we send messages with a unique message ID that is guarded by our dedupe layer (https://segment.com/blog/exactly-once-delivery/).
For us, our retry policy should be (as per https://paper.dropbox.com/doc/analytics-foo-library-guidelines-2trBhLKQD4Soz4VatvuGR#:uid=189560039280582553736180&h2=Handling-Network-Errors):
1. Retry network errors (socket timed out, etc.)
2. Retry server errors (HTTP 5xx)
3. Retry HTTP 429.
> Improve Retry Behaviour.

- index.js
- package.json
- test.js
Both use the node crypto package on Node apps so there shouldn't be a meaningful difference here.
The differences come in the browser. crypto-token works in the browser by polyfilling the crypto package. node-uuid works by using the browser crypto apis if available, otherwise falling back to Math.random() (https://github.com/kelektiv/node-uuid/blob/master/lib/rng-browser.js).
Because of polyfilling on the browser, crypto-token contributes 90kb to our library in the browser which is rougly 80% of the library size on the browser (the rest of the library is only 20kb). node-uuid only adds 1kb (though I believe this comes at the cost of generating slightly less random messageIds on the browser). I don't think the extra weight is worth the cost, especially as we're not using this in a critical …
> Replace crypto-token with uuid.

- index.js
- package.json
Sometimes we need to delay retry to avoid high CPU consumes during retry, especially when we set `retryCount` to big number.
> Need to Delay Retry

- .buildscript/bootstrap.sh
- Makefile
- package.json
Instead of defining targets here, we delegate to Yarn for most targets.
> add standardized makefile

- .buildscript/e2e.sh
- cli.js
- package.json
- test.js
Instead of our handrolled end to end testing code, use library-e2e-tester which is more consistent and supports more message types.
Requires refactoring the existing cli.js file to match the library-e2e-tester interface
> Use library-e2e-tester 

- package.json
The current npm package bundles a CLI, which adds some unnecessary bloat to the package size. This PR removes this bloat, and will be moved to a separate repo/package.
> refactor: move cli to a sub-package

- .buildscript/e2e.sh
- cli.js
- package.json
- yarn.lock
* remove nsp check as it is deprecated (https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting). we already have a replacement with Snyk.
* upgrade handlebar dependency (https://snyk.io/vuln/SNYK-JS-HANDLEBARS-173692)
> fix builds

- .circleci/config.yml
- package.json
- test.js
- yarn.lock
Snyk alert: https://app.snyk.io/org/segment-pro/project/cf7257d6-cfcf-49ce-a652-81ce8bdbca59#issue-SNYK-JS-HANDLEBARS-174183
Version check:
```bash
➜  analytics-node git:(dev-deps/update) yarn why handlebars
yarn why v1.16.0
[1/4] 🤔  Why do we have the module "handlebars"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "handlebars@4.1.2"
info Reasons this module exists
- "nyc#istanbul-reports" depends on it
- Hoisted from "nyc#istanbul-reports#handlebars"
info Disk size without dependencies: "2.7MB"
info Disk size with unique dependencies: "4.56MB"
info Disk size with transitive dependencies: "4.72MB"
info Number of shared dependencies: 5
✨  Done in 0.67s.
```
I changed the node 6 test env to 12, as 6 reached EOL and …
> Upgrade devDependencies

- .circleci/config.yml
Previously the publish step would only run on tags such as `3.4.0-beta`, however, with `np` we name tags with a `v` prefix (e.g. `v3.4.0-beta`), causing the publish job step to never run.
This updates the tag regex filter to allow the publish step to run on tags like `v3.4.0-beta`.
> ci: fix publish step

- .circleci/config.yml
we moved some tokens around, and the NPM_AUTH variable is available via the npm context in Circle CI.
> add npm context to publish step

- .circleci/config.yml
context is declared on the workflow, rather than the job.
```
> circleci config validate -c .circleci/config.yml
.circleci/config.yml is valid
```
> fix context declaration

- .circleci/config.yml
As Nick pointed out in https://github.com/segmentio/analytics-node/pull/216#discussion_r295932570, this should be on the specific step in the job.
```
> circleci config validate -c .circleci/config.yml
Config file at .circleci/config.yml is valid.
```
> attach `npm` context to publish job

- index.js
- package.json
- test.js
- yarn.lock
This merge seeks to address two issues:
1. Fix the infinite retry bug associated with axios 0.19.0
2. Prevent axios-retry options from leaking into other codebases that are using axios
To address the first concern I've updated the current version of axios to 0.19.2 which contains the necessary fixes for avoiding infinite retries within axios when the HTTP response is within the 5xx range. 
As per the second concern, I've configured the Analytics class to instead use it's own axios client, thereby preventing client options from leaking into other axios instances. 
Unit tests have been added to validate that the retries are in fact working and that option leakage is no longer occuring.
> Fix for infinite axios-retry on 5xx responses and axios client option leakage

- index.js
Fixes: https://github.com/segmentio/analytics-node/issues/230
> Fix data parameter always undefined on callback for track method

- package.json
- yarn.lock
Vulnerability: https://www.huntr.dev/bounties/1e8f07fc-c384-4ff9-8498-0690de2e8c31/
Vulnerability fix: https://github.com/axios/axios/pull/3980
Axios Releases: https://github.com/axios/axios/releases
In versions 0.19.1-0.21.1, there is an exploit to trigger a ReDoS attack.
The versions in the package.json are good enough to allow people to manually bump to a fixed version, but also good to prevent this in the first place :)
> Bumped axios version to patch ReDoS vulnerability

- index.js
Updating the queue size limit to flush when approaching instead of surpassing.
> Flush when approaching the limit instead of surpassing the limit

- index.js
- test.js
This pull request resolves issue #310.
`If a callback function in the messages queue or the callback function passed to flush throws an error, it will trigger the .catch () handler in the axios promise chain and run the thrown error through the error handling code meant for axios errors. This also results in the callback being called twice.`
> done function updated

- index.js
- test.js
✔️ All existing tests pass
✔️ New functionality is unit-tested
Addresses #320 #326 
This PR adds an optional `errorHandler` property to the class constructor's options.
If unspecified, the behaviour of the library does not change.
If specified, when an axios request fails, `errorHandler(axiosError)` will be called instead of re-throwing the axios error.
Example usage:
```js
const Analytics = require('analytics-node');
const client = new Analytics('write key', {
errorHandler: (err) => {
console.error('analytics-node flush failed.')
console.error(err)
}
});
client.track({
event: 'event name',
userId: 'user id'
});
// ☝️ if this fails when flushed no exception will be thrown and instead
// the axios error will be logged to the console.
```
Since no way to handle the re-thrown axios error was …
> Add an errorHandler property to constructor options

- index.js
- test.js
I work at Trello @ Atlassian.
We use this library, however, it started causing problems for us when `throw err` was added to the `.flush()` method. This has been documented here. (#320) For us it was resulting in process crashes when we receive an error message (like a 429) when emitting an event. We had to pin the version of this library to a version before this behavior was added.
I saw, that the `errorHandler` property was added (#342) and was attempting to update our code to use it, however, when writing a test case, I saw that my event callback was never invoked when `errorHandler` was present and called 
This is because, in the `.flush()`, everywhere else the method can end, we call `done(err)`, however we do not when looking for and invoking the `errorHandler`. To reiterate the …
> Ensure callback is called when invoking errorHanlder

- index.js
Simple fix so flush waits for previous inflight messages to be sent.
Resolves https://github.com/segmentio/analytics-node/issues/309
> flush: guarantee that all inflight messages are sent 
