segmentio/analytics-node

package.json

remove the duplicated keyword

---

Makefile
package.json
test/index.js

Hi, I'm using "analytics-node" in a project and I realized that this repo is using libraries with known vulnerabilities. So I've added [Node Security Project](https://nodesecurity.io) support and I've also updated the conflictive ones.
Could you please take a look? :)
Thanks!

Found known vulnerabilities in dependencies

---

lib/index.js
package.json
test/index.js

cc @stephenmathieson 
We're going to need https://github.com/segmentio/loosely-validate-event/pull/1

add support for screen events

---

lib/index.js

- It would reduce significant amount of bundled file size when using the library with webpack

Preventing webpack to bundle all lodash lib

---

lib/index.js
package.json

#100 #101 #106
I'm trying this with a fresh branch rebased off of origin/master

Remove superagent-retry module

---

lib/index.js

Fixes https://github.com/segmentio/analytics-node/issues/34.

Skip data in flush callbacks

---

index.js
package.json
test.js

This patch removes our dependency on superagent and replaces it with
axios.
Axios:
- works in the browser
- can be browserified
- works in node
- doesn't leak globals
- has no (known) security vulnerabilities
- is better maintained than superagent
Closes #124.

replace superagent with axios

---

index.js

Fix: @angular/cli@1.4.5 Error by adding json file extension

---

index.js
package.json

Fixes https://github.com/segmentio/analytics-node/issues/91.

Remove usage of debug module

---

History.md

This reverts commit 547a001e4a5f72bd94fb06155f37f5ee695155da.
@f2prateek what tool do you use to generate a changelog? I searched for `git-changelog`, but haven't found one that generates a similar output to what we have.

Add changelog back

---

index.js
test.js

https://tools.ietf.org/html/rfc7231#section-5.5.3
We didn't originally standardize this, but have this documented now https://paper.dropbox.com/doc/analytics-foo-library-guidelines-2trBhLKQD4Soz4VatvuGR#:uid=631141099033910690508560&h2=User-Agent.

Make user agent RFC 7231 compliant.

---

circle.yml
package.json

Currently I'm not enforcing the limit anywhere. This will be just used as a tool to measure our size every once in a while for now.

Add Size Limit script.

---

index.js

Only set User-Agent header on browser.

---

index.js
test.js

Addresses #116, follow up from #118

Add `enable` option to disable flushing

---

test.js

Runscope shutdown the traffic inspector (https://blog.runscope.com/posts/phasing-out-traffic-inspector) we were using for our tests.
This migrates to the custom webhook replacement we had built.

Migrate E2E tests from Runscope to Segment webhook

---

cli.js

This PR adds support to the CLI for overriding the endpoint/host which is useful for testing.

feat(cli): add ability to override host/api url

---

.buildscript/e2e.sh

use newer version of e2e harness and a higher concurrency

run e2e tests concurrently

---

index.js

The comment didn't reflect what was happening on the code.
Fixed it.

Fixed a typo to reflect actual code behaviour

---

index.js

When initializing the SDK, allows the developer to have a customized path for sending batch events

Allow to update endpoint to send batch events

---

index.js

I have an Electron app using axios for HTTP where I am using a custom adapter to get around proxy issues by using Electron's `net` module.
The current version of `analytics-node` doesn't expose any configuration for `axios`, so I added the following `options` properties:
- `axiosConfig`: configuration options for creating an axios instance if you don't have axios as a dependency
- `axiosInstance`: instance of axios if you already have axios as a dependency, maybe with a different version
It's not ideal from a library-coupling perspective, but I didn't see an easy way to avoid that without 
defining some library-agnostic interface for the HTTP adapter which would still support retries, which seems overkill.
I just thought I would post this PR in case it was a useful enhancement. 
One …

Feature: Allow passing axios instance or config in options.

---

index.js
test.js

Closes https://github.com/segmentio/analytics-node/issues/244

throws error when message is over 32kb

---

index.js
test.js

Solves the issue that callback was calling twice.
- All tests working.
- Related to issue #303 #305 and #308.
- An improvement from pr #299

Callback called twice

---

readme.md

Following the [documentation example here](https://segment.com/docs/connections/sources/catalog/libraries/server/node/#track) as well as the official `analytics-node` API signature, this code snippet example needs to be updated. The current example is from `analytics.js`, Segment's clientside library.
NOTE: userId (or anonymousId) is required for analytics-node events

Update code snippet to match analyics-code API

---

package.json
yarn.lock

Solve the issue: [#337](https://github.com/segmentio/analytics-node/issues/337)

Update library axios to 0.27.2

---

readme.md

Add sentAt note to readme
